### ISSUE TITLE
can't set up

### ISSUE THREAD

**Issue by liseeocean** [openstreams/wflow#14]
use  anaconda2.5 and follow your requests ,i can't set up wflow.The questions is :
 UserWarning: The version specified ('1.0.master') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

**Comment by visr** [comment]
Apologies for taking so long to respond. Both the installation instructions and the version number scheme have improved since you posted your issue. It should be in compliance with PEP 440 now, see release 2018.1 that was released today. Do let us know if you still have issues with the installation.
