### ISSUE TITLE
Roughness not updated correctly

### ISSUE THREAD

**Issue by tuggegese** [openstreams/wflow#48]
Dear all,

Correct me if I am wrong, but think there is a bug when updating the Manning roughness within the configuration file. For example:
`[variable_change_once]`
`self.N = self.N * 10`
is not recognized.

I think the problem is that the  `wf_multparameters()` function within the initialization step (see function `def initial(self)` in the `WflowModel` class) is called at the wrong place. Currently, `wf_multparameters()` is called after estimating the alpha term for the kinematic wave (see `self.AlpTermL = pow((self.N / (pcr.sqrt(self.landSlope))), self.Beta)`). This leads to updating the N parameter for the output, but for the calculations the original parameter is used.

Best regards,
Sebastian

**Comment by pipipercy** [comment]
Hi,

I have found a issue in notebooks/wflow_prepare

in "in [12]:", the code is incomplete.

Best wish

**Comment by verseve** [comment]
I did move `wf_multparameters()` in commit https://github.com/openstreams/wflow/commit/0a97d513dce24d18d74b0ccdab3cf00904b6a9e4, so that only model parameters that are directly read by Wflow can be changed through this function, this means that dependent model parameters can not be changed. Please let me know if this solves your issue.
